package forfoodmvc.modelo;
// Generated 13/09/2016 11:16:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer carCodigo;
     private String carNome;
     private String carDescricao;
     private float carSalario;
     private Set funcionarios = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String carNome, String carDescricao, float carSalario) {
        this.carNome = carNome;
        this.carDescricao = carDescricao;
        this.carSalario = carSalario;
    }
    public Cargo(String carNome, String carDescricao, float carSalario, Set funcionarios) {
       this.carNome = carNome;
       this.carDescricao = carDescricao;
       this.carSalario = carSalario;
       this.funcionarios = funcionarios;
    }
   
    public Integer getCarCodigo() {
        return this.carCodigo;
    }
    
    public void setCarCodigo(Integer carCodigo) {
        this.carCodigo = carCodigo;
    }
    public String getCarNome() {
        return this.carNome;
    }
    
    public void setCarNome(String carNome) {
        this.carNome = carNome;
    }
    public String getCarDescricao() {
        return this.carDescricao;
    }
    
    public void setCarDescricao(String carDescricao) {
        this.carDescricao = carDescricao;
    }
    public float getCarSalario() {
        return this.carSalario;
    }
    
    public void setCarSalario(float carSalario) {
        this.carSalario = carSalario;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


