package forfoodmvc.modelo;
// Generated 13/09/2016 11:16:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cliCpf;
     private String cliNome;
     private int cliFone;
     private String cliEndereco;
     private Set pedidos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int cliCpf, String cliNome, int cliFone, String cliEndereco) {
        this.cliCpf = cliCpf;
        this.cliNome = cliNome;
        this.cliFone = cliFone;
        this.cliEndereco = cliEndereco;
    }
    public Cliente(int cliCpf, String cliNome, int cliFone, String cliEndereco, Set pedidos) {
       this.cliCpf = cliCpf;
       this.cliNome = cliNome;
       this.cliFone = cliFone;
       this.cliEndereco = cliEndereco;
       this.pedidos = pedidos;
    }
   
    public int getCliCpf() {
        return this.cliCpf;
    }
    
    public void setCliCpf(int cliCpf) {
        this.cliCpf = cliCpf;
    }
    public String getCliNome() {
        return this.cliNome;
    }
    
    public void setCliNome(String cliNome) {
        this.cliNome = cliNome;
    }
    public int getCliFone() {
        return this.cliFone;
    }
    
    public void setCliFone(int cliFone) {
        this.cliFone = cliFone;
    }
    public String getCliEndereco() {
        return this.cliEndereco;
    }
    
    public void setCliEndereco(String cliEndereco) {
        this.cliEndereco = cliEndereco;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


