package forfoodmvc.modelo;
// Generated 13/09/2016 11:16:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer funCodigo;
     private Cargo cargo;
     private int Cargo_carCodigo;
     private String funNome;
     private String funEndereco;
     private int funFone;
     private String funSenha;
     private int funCpf;
     private Set pedidos = new HashSet(0);

    public Funcionario() {
    }

    public Funcionario(Integer funCodigo, Cargo cargo, String funNome, String funEndereco, int funFone, String funSenha, int funCpf) {
        this.funCodigo = funCodigo;
        this.cargo = cargo;
        this.funNome = funNome;
        this.funEndereco = funEndereco;
        this.funFone = funFone;
        this.funSenha = funSenha;
        this.funCpf = funCpf;
    }

    public int getCargo_carCodigo() {
        return Cargo_carCodigo;
    }

    public void setCargo_carCodigo(int Cargo_carCodigo) {
        this.Cargo_carCodigo = Cargo_carCodigo;
    }
    
    

    public Integer getFunCodigo() {
        return funCodigo;
    }

    public void setFunCodigo(Integer funCodigo) {
        this.funCodigo = funCodigo;
    }

    public Cargo getCargo() {
        return cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    public String getFunNome() {
        return funNome;
    }

    public void setFunNome(String funNome) {
        this.funNome = funNome;
    }

    public String getFunEndereco() {
        return funEndereco;
    }

    public void setFunEndereco(String funEndereco) {
        this.funEndereco = funEndereco;
    }

    public int getFunFone() {
        return funFone;
    }

    public void setFunFone(int funFone) {
        this.funFone = funFone;
    }

    public String getFunSenha() {
        return funSenha;
    }

    public void setFunSenha(String funSenha) {
        this.funSenha = funSenha;
    }

    public int getFunCpf() {
        return funCpf;
    }

    public void setFunCpf(int funCpf) {
        this.funCpf = funCpf;
    }

    public Set getPedidos() {
        return pedidos;
    }

    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

	
  




}


