package forfoodmvc.modelo;
// Generated 13/09/2016 11:16:18 by Hibernate Tools 4.3.1



/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer pedCodigo;
     private Cliente cliente;
     private Funcionario funcionario;
     private Prato prato;
     private boolean pedStatus;
     private float pedValorTotal;
     private int pedMesa;
     private int pedQuantidade;
     private String pedData;

    public Pedido() {
    }

	
    public Pedido(Funcionario funcionario, Prato prato, boolean pedStatus, float pedValorTotal, int pedMesa, int pedQuantidade, String pedData) {
        this.funcionario = funcionario;
        this.prato = prato;
        this.pedStatus = pedStatus;
        this.pedValorTotal = pedValorTotal;
        this.pedMesa = pedMesa;
        this.pedQuantidade = pedQuantidade;
        this.pedData = pedData;
    }
    public Pedido(Cliente cliente, Funcionario funcionario, Prato prato, boolean pedStatus, float pedValorTotal, int pedMesa, int pedQuantidade, String pedData) {
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.prato = prato;
       this.pedStatus = pedStatus;
       this.pedValorTotal = pedValorTotal;
       this.pedMesa = pedMesa;
       this.pedQuantidade = pedQuantidade;
       this.pedData = pedData;
    }
   
    public Integer getPedCodigo() {
        return this.pedCodigo;
    }
    
    public void setPedCodigo(Integer pedCodigo) {
        this.pedCodigo = pedCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Prato getPrato() {
        return this.prato;
    }
    
    public void setPrato(Prato prato) {
        this.prato = prato;
    }
    public boolean isPedStatus() {
        return this.pedStatus;
    }
    
    public void setPedStatus(boolean pedStatus) {
        this.pedStatus = pedStatus;
    }
    public float getPedValorTotal() {
        return this.pedValorTotal;
    }
    
    public void setPedValorTotal(float pedValorTotal) {
        this.pedValorTotal = pedValorTotal;
    }
    public int getPedMesa() {
        return this.pedMesa;
    }
    
    public void setPedMesa(int pedMesa) {
        this.pedMesa = pedMesa;
    }
    public int getPedQuantidade() {
        return this.pedQuantidade;
    }
    
    public void setPedQuantidade(int pedQuantidade) {
        this.pedQuantidade = pedQuantidade;
    }
    public String getPedData() {
        return this.pedData;
    }
    
    public void setPedData(String pedData) {
        this.pedData = pedData;
    }




}


