/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forfoodmvc.visao;

import forfoodmvc.controle.FuncionarioControle;
import forfoodmvc.controle.PratoControle;
import forfoodmvc.modelo.Funcionario;
import forfoodmvc.modelo.Pedido;
import forfoodmvc.controle.PedidoControle;

import forfoodmvc.modelo.Prato;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alunos
 */
public class CadastroPedidoGUI extends javax.swing.JFrame {

    private DefaultListModel modelo = new DefaultListModel();
    ArrayList<Pedido> listarPedido;

    /**
     * Creates new form FrmModeloGUI
     */
    public CadastroPedidoGUI() {
        initComponents();

        preencheComboFunc();
        preencheComboPrato();
        listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxNumeroMesa = new javax.swing.JComboBox<>();
        jComboBoxPago = new javax.swing.JComboBox<>();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPrato = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxQuantidade = new javax.swing.JComboBox<>();
        jButton1Inserir = new javax.swing.JButton();
        jTextFieldValorFinaol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ForFood - Cadastro Pedido");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Numero da Mesa:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        jLabel3.setText("Pedido Pago?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 80, 10));

        jLabel4.setText("Funcionário:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 44, 84, -1));

        jLabel6.setText("Codigo do Prato:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 77, 84, -1));

        jComboBoxNumeroMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9 ", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", " " }));
        jComboBoxNumeroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNumeroMesaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxNumeroMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 13, 393, -1));

        jComboBoxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jPanel1.add(jComboBoxPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 381, 20));

        jComboBoxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 44, 393, -1));

        jLabel7.setText("Valor Total Pedido:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, -1));

        jComboBoxPrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBoxPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPratoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 74, 150, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pratos pedidos"));

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel9.setText("Quantidade:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 87, -1, -1));

        jComboBoxQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "100" }));
        jPanel1.add(jComboBoxQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 74, 54, 30));

        jButton1Inserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/food.png"))); // NOI18N
        jButton1Inserir.setText("Inserir");
        jButton1Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1InserirActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Inserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 74, 111, -1));

        jTextFieldValorFinaol.setEditable(false);
        jTextFieldValorFinaol.setText("0");
        jTextFieldValorFinaol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorFinaolActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldValorFinaol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 70, 30));

        jLabel5.setText("Data:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, -1));

        jTextFieldData.setText("??/??/??");
        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 390, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 454));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Mesa", "Funcionario", "Valor Total", "Pago", "Prato", "Codigo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 486, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 41, -1, 450));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu de Opções", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 51))); // NOI18N

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/SalvarIcone.png"))); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/AlterarIcone.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/DeletarIcone.png"))); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CancelarIcone.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/VoltarIcone.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonDeletar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/PedidoIcone.png"))); // NOI18N
        jLabel2.setText("Cadastro de Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        ArrayList<String> arrP = new ArrayList<String>();

        Pedido p = new Pedido();
        PedidoControle pC = new PedidoControle();
        //---------------------------------------------------------------------------------
        p.setPedMesa(Integer.parseInt(jComboBoxNumeroMesa.getSelectedItem().toString()));
        //---------------------------------------------------------------------------------
        if (jComboBoxPago.getSelectedItem().equals("Sim")) {
            p.setPedStatus(true);
        } else if (jComboBoxPago.getSelectedItem().equals("Não")) {
            p.setPedStatus(false);
        }
        //---------------------------------------------------------------------------------
        p.setPedValorTotal(Float.parseFloat(jTextFieldValorFinaol.getText()));
        //---------------------------------------------------------------------------------
        String funcionario = (String) jComboBoxFuncionario.getSelectedItem();
        String[] parts = funcionario.split("-");
        int cod = Integer.parseInt(parts[0]);
        System.out.println(cod);
        p.setPed_funCodigo(cod);
        //---------------------------------------------------------------------------------
        p.setData(jTextFieldData.getText().toString());
        //---------------------------------------------------------------------------------
        p.setQuantidade(Integer.parseInt((String) jComboBoxQuantidade.getSelectedItem()));
        //---------------------------------------------------------------------------------
        String prato = (String) jComboBoxPrato.getSelectedItem();
        String[] parts1 = prato.split("-");
        int cod1 = Integer.parseInt(parts1[0]);
        p.setPed_praCodigo(cod1);
        //---------------------------------------------------------------------------------
        pC.adiciona(p);
        JOptionPane.showConfirmDialog(null, " Cadastro realizado com sucesso!");

        listar();

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        new PrincipalGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jComboBoxNumeroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNumeroMesaActionPerformed

    }//GEN-LAST:event_jComboBoxNumeroMesaActionPerformed

    private void jComboBoxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionarioActionPerformed

    }//GEN-LAST:event_jComboBoxFuncionarioActionPerformed

    private void jComboBoxPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPratoActionPerformed

    private void jButton1InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1InserirActionPerformed
        PratoControle pc = new PratoControle();
        ArrayList<Prato> arrP = new ArrayList<Prato>();
        arrP = pc.listarPratoCodigo();

        String linhaCombo = (String) jComboBoxPrato.getSelectedItem();
        String[] parts = linhaCombo.split("-");
        int cod = Integer.parseInt(parts[0]);
        float preco = 0;
        for (Prato arrP1 : arrP) {
            if (arrP1.getCod() == cod) {
                float precoAntigo = Float.parseFloat(jTextFieldValorFinaol.getText());
                preco = arrP1.getPreco();
                float quantidade = Float.parseFloat((String) jComboBoxQuantidade.getSelectedItem());
                float novoPreco = precoAntigo + (preco * quantidade);
                jTextFieldValorFinaol.setText(String.valueOf(novoPreco));
                break;
            }
        }
        modelo.addElement(linhaCombo);
        jList1.setModel(modelo);
    }//GEN-LAST:event_jButton1InserirActionPerformed

    private void jTextFieldValorFinaolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorFinaolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorFinaolActionPerformed

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed

        int linha = jTable2.getSelectedRow();
        Pedido p = new Pedido();

        jTable2.setValueAt(jTextFieldData.getText(), linha, 0);
        jTable2.setValueAt(jComboBoxNumeroMesa.getSelectedItem(), linha, 1);
        jTable2.setValueAt(jComboBoxFuncionario.getSelectedItem(), linha, 2);
        jTable2.setValueAt(Float.parseFloat(jTextFieldValorFinaol.getText()), linha, 3);
        jTable2.setValueAt((String) jComboBoxPago.getSelectedItem(), linha, 4);
        jTable2.setValueAt(jComboBoxPrato.getSelectedItem(), linha, 5);

        p.setPedCodigo((int) jTable2.getValueAt(linha, 6));
        //---------------------------------------------------------------------------------
        p.setPedMesa(Integer.parseInt(jComboBoxNumeroMesa.getSelectedItem().toString()));
        //---------------------------------------------------------------------------------
        if (jComboBoxPago.getSelectedItem().equals("Sim")) {
            p.setPedStatus(true);
        } else if (jComboBoxPago.getSelectedItem().equals("Não")) {
            p.setPedStatus(false);
        }
        //---------------------------------------------------------------------------------
        p.setPedValorTotal(Float.parseFloat(jTextFieldValorFinaol.getText()));
        //---------------------------------------------------------------------------------
        String funcionario = (String) jComboBoxFuncionario.getSelectedItem();
        String[] parts = funcionario.split("-");
        int cod = Integer.parseInt(parts[0]);
        //System.out.println(cod);
        p.setPed_funCodigo(cod);
        //---------------------------------------------------------------------------------
        p.setData(jTextFieldData.getText().toString());
        //---------------------------------------------------------------------------------
        p.setQuantidade(Integer.parseInt((String) jComboBoxQuantidade.getSelectedItem()));
        //---------------------------------------------------------------------------------
        String prato = (String) jComboBoxPrato.getSelectedItem();
        String[] parts1 = prato.split("-");
        int cod1 = Integer.parseInt(parts1[0]);
        p.setPed_praCodigo(cod1);
        //---------------------------------------------------------------------------------

        PedidoControle pedidoControl = new PedidoControle();
        pedidoControl.atualizar(p);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed

        Pedido p = new Pedido();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int index = jTable2.getSelectedRow();

        p.setPedCodigo((int) jTable2.getValueAt(index, 6));
        PedidoControle pedidoControl = new PedidoControle();
        pedidoControl.deletar(p);

        model.removeRow(index);

        jTextFieldValorFinaol.setText("");
        jTextFieldData.setText("");


    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int linha = jTable2.getSelectedRow(); //retorna um inteiro

        jTextFieldData.setText((String) jTable2.getValueAt(linha, 0).toString());
        jTextFieldValorFinaol.setText((String) jTable2.getValueAt(linha, 3).toString());
        //jTextFieldTempo.setText((String)jTable2.getValueAt(linha, 4).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldData.setText("");
        jTextFieldValorFinaol.setText("");
        jComboBoxFuncionario.setSelectedIndex(0);
        jComboBoxNumeroMesa.setSelectedIndex(0);
        jComboBoxPago.setSelectedIndex(0);
        jComboBoxQuantidade.setSelectedIndex(0);
        jComboBoxPrato.setSelectedIndex(0);
        
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Inserir;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxNumeroMesa;
    private javax.swing.JComboBox<String> jComboBoxPago;
    private javax.swing.JComboBox<String> jComboBoxPrato;
    private javax.swing.JComboBox<String> jComboBoxQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldValorFinaol;
    // End of variables declaration//GEN-END:variables

    //preenche o comboBox de Funcionario com os dados do banco
    private void preencheComboFunc() {
        FuncionarioControle fc = new FuncionarioControle();
        ArrayList<Funcionario> arrF = new ArrayList<Funcionario>();
        arrF = fc.listarFuncionarioCodigo();

        for (Funcionario arrF1 : arrF) {
            String dadosFunc = String.valueOf(arrF1.getCodigo()) + "-" + arrF1.getNome();
            jComboBoxFuncionario.addItem(dadosFunc);
        }
    }

    //preenche o comboBox de Pratos com os dados do banco
    private void preencheComboPrato() {
        PratoControle fc = new PratoControle();
        ArrayList<Prato> arrF = new ArrayList<Prato>();
        arrF = fc.listarPratoCodigo();

        for (Prato arrF1 : arrF) {
            String dadosFunc = String.valueOf(arrF1.getCod()) + "-" + arrF1.getNome();
            jComboBoxPrato.addItem(dadosFunc);
        }
    }
    //---------------------------------------------------------------------------------------------------------------------------------

    private void preencherTabela(ArrayList<Pedido> pedido) {
        DefaultTableModel modeloTable = new DefaultTableModel();
        modeloTable = (DefaultTableModel) jTable2.getModel();
        String x = null;
        while (modeloTable.getRowCount() > 0) {
            modeloTable.removeRow(0);
        }
        for (Pedido p : pedido) {
            if (p.isPedStatus() == true) {
                x = "Sim";
            } else if (p.isPedStatus() == false) {
                x = "Não";
            }

            modeloTable.addRow(new Object[]{p.getData(), p.getPedMesa(), p.getPed_funCodigo(), p.getPedValorTotal(), x, p.getPed_praCodigo(), p.getPedCodigo()});

        }
    }

    private void listar() {
        PedidoControle pedControl = new PedidoControle();
        listarPedido = pedControl.listar();
        preencherTabela(listarPedido);
        for (Pedido listarPedido1 : listarPedido) {
            System.out.println(listarPedido1.toString());
        }
    }

}
