-- MySQL Script generated by MySQL Workbench
-- 07/29/16 14:39:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ForFood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ForFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ForFood` DEFAULT CHARACTER SET utf8 ;
USE `ForFood` ;

-- -----------------------------------------------------
-- Table `ForFood`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ForFood`.`Cargo` (
  `carCodigo` INT NOT NULL AUTO_INCREMENT,
  `carNome` VARCHAR(45) NOT NULL,
  `carDescricao` VARCHAR(45) NOT NULL,
  `carSalario` FLOAT NOT NULL,
  PRIMARY KEY (`carCodigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForFood`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ForFood`.`Funcionario` (
  `funCodigo` INT NOT NULL AUTO_INCREMENT,
  `funNome` VARCHAR(45) NOT NULL,
  `funEndereco` VARCHAR(45) NOT NULL,
  `funFone` INT NOT NULL,
  `funSenha` VARCHAR(45) NOT NULL,
  `Cargo_carCodigo` INT NOT NULL,
  `funCpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`funCodigo`),
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_carCodigo`)
    REFERENCES `ForFood`.`Cargo` (`carCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Funcionario_Cargo1_idx` ON `ForFood`.`Funcionario` (`Cargo_carCodigo` ASC);


-- -----------------------------------------------------
-- Table `ForFood`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ForFood`.`Prato` (
  `praCodigo` INT NOT NULL AUTO_INCREMENT,
  `praNome` VARCHAR(45) NOT NULL,
  `praDescricao` VARCHAR(45) NOT NULL,
  `praTempo` INT NOT NULL,
  `praPreco` FLOAT NOT NULL,
  PRIMARY KEY (`praCodigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForFood`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ForFood`.`Cliente` (
  `cliCpf` INT NOT NULL,
  `cliNome` VARCHAR(45) NOT NULL,
  `cliFone` INT NOT NULL,
  `cliEndereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliCpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ForFood`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ForFood`.`Pedido` (
  `Funcionario_funCodigo` INT NOT NULL,
  `pedCodigo` INT NOT NULL AUTO_INCREMENT,
  `pedStatus` TINYINT(1) NOT NULL,
  `pedValorTotal` FLOAT NOT NULL,
  `pedMesa` INT NOT NULL,
  `Cliente_cliCpf` INT NULL,
  `pedQuantidade` INT NOT NULL,
  `pedData` TEXT NOT NULL,
  `Prato_praCodigo` INT NOT NULL,
  PRIMARY KEY (`pedCodigo`),
  CONSTRAINT `fk_Mesa_Pedido_Funcionario1`
    FOREIGN KEY (`Funcionario_funCodigo`)
    REFERENCES `ForFood`.`Funcionario` (`funCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_cliCpf`)
    REFERENCES `ForFood`.`Cliente` (`cliCpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Prato1`
    FOREIGN KEY (`Prato_praCodigo`)
    REFERENCES `ForFood`.`Prato` (`praCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mesa_Pedido_Funcionario1_idx` ON `ForFood`.`Pedido` (`Funcionario_funCodigo` ASC);

CREATE INDEX `fk_Pedido_Cliente1_idx` ON `ForFood`.`Pedido` (`Cliente_cliCpf` ASC);

CREATE INDEX `fk_Pedido_Prato1_idx` ON `ForFood`.`Pedido` (`Prato_praCodigo` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
