/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forfoodmvc.visao;

/**
 *
 * @author Alunos
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonCadastroPedido = new javax.swing.JButton();
        jButtonCadastroFuncionario = new javax.swing.JButton();
        jButtonCadastroCargo = new javax.swing.JButton();
        jButtonCadastroPrato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ForFood - Principal");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToolBar1.setRollover(true);

        jButtonCadastroPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/PedidoIcone.png"))); // NOI18N
        jButtonCadastroPedido.setFocusable(false);
        jButtonCadastroPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastroPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPedidoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastroPedido);

        jButtonCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/FuncionarioIcone.png"))); // NOI18N
        jButtonCadastroFuncionario.setFocusable(false);
        jButtonCadastroFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastroFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFuncionarioActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastroFuncionario);

        jButtonCadastroCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/job-search-symbol-of-suitcase-and-curriculum-paper.png"))); // NOI18N
        jButtonCadastroCargo.setFocusable(false);
        jButtonCadastroCargo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastroCargo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastroCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCargoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastroCargo);

        jButtonCadastroPrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/food.png"))); // NOI18N
        jButtonCadastroPrato.setFocusable(false);
        jButtonCadastroPrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastroPrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastroPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPratoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastroPrato);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/users.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ForFoodLOGO2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(88, 88, 88))
        );

        jMenuArquivo.setText("Arquivo");
        jMenuBar2.add(jMenuArquivo);

        jMenuEditar.setText("Editar");
        jMenuBar2.add(jMenuEditar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFuncionarioActionPerformed
        new CadastroFunGUI().setVisible(true);
    }//GEN-LAST:event_jButtonCadastroFuncionarioActionPerformed

    private void jButtonCadastroPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPratoActionPerformed
         new CadastrarPratoGUI().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButtonCadastroPratoActionPerformed

    private void jButtonCadastroCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCargoActionPerformed
        new CadastroCargoGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastroCargoActionPerformed

    private void jButtonCadastroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPedidoActionPerformed
        new CadastroPedidoGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCadastroPedidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new CadastroClienteGUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastroCargo;
    private javax.swing.JButton jButtonCadastroFuncionario;
    private javax.swing.JButton jButtonCadastroPedido;
    private javax.swing.JButton jButtonCadastroPrato;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
